import type { Metadata } from "next";
import Link from "next/link";
import { PageIntro } from "@/components/imageworks/page-intro";
import { ServiceCover } from "@/components/imageworks/service-pathways";
import { ServiceReading } from "@/components/imageworks/journal-cards";
import { Faq } from "@/components/imageworks/faq";
import { FinalCta } from "@/components/imageworks/final-cta";
import { SERVICE_CATALOG } from "@/lib/service-catalog";
const title="Other Tech Solutions — Integrations & Infrastructure | Fortitudo";
const description="Connect your systems, repair fragile workflows and build the technical foundations your business needs. APIs, MCP, context systems and infrastructure.";
export const metadata:Metadata={title,description,alternates:{canonical:"https://www.fortitudo.agency/services/other-tech-solutions"},openGraph:{title,description,images:[{url:"https://www.fortitudo.agency/journal/tech-v2.webp",width:1120,height:1400}]}};
const solutions=[
 ["Connect the systems you already use","CRM, commerce, booking, email and internal data connections. We map record ownership and failure paths, then build the connection around the business outcome.","mcp-and-api"],
 ["Give AI useful context","Knowledge retrieval, vector search and memory systems grounded in approved business information, with permissions and update behavior defined before use.","context-and-memory"],
 ["Build the operating environment","Agent harnesses, tool access, execution controls and the infrastructure needed to operate an agreed workflow. Provider access and ongoing costs are confirmed for the actual project.","agent-infrastructure"],
 ["Put structured decisions into a workflow","A scoped Jev integration for a specific decision, with the inputs, outputs and review criteria defined. We validate the decision path in the system where it will be used.","jev-implementation"],
 ["Connect creative production","Image, video and audio workflows that move approved inputs through generation, review and delivery. Model availability, licensing and usage limits shape the scope.","creative-ai-workflows"],
 ["Repair and configure","Diagnosis, AI environment setup and practical team handover. Start with the system you have and the problem to solve, rather than assuming a complete rebuild.","ai-setup-and-consulting"],
];
export default function OtherTech(){return <>
 <PageIntro label="Other tech solutions" title="Make the pieces work together." lead="The connection between two systems. The workflow your team repeats. The infrastructure behind an AI product. We build and repair the technical pieces that keep the business moving."/>
 <ServiceCover slug="other-tech-solutions"/>
 <section className="mx-auto max-w-[1440px] px-4 pb-24 sm:px-6"><div className="grid gap-12 border-y border-border py-10 lg:grid-cols-2"><div><p className="text-sm text-muted-foreground">A focused technical engagement</p><h2 className="mt-4 text-4xl leading-tight tracking-tight">Start with the problem.<br/>Scope the right solution.</h2><p className="mt-6 max-w-xl text-base leading-8 text-muted-foreground">Bring the current tools, the desired result and an example of what is failing or missing. We review the dependencies, identify a practical approach and define what a working result means before implementation.</p><Link href="/contact?service=software_solutions" className="mt-7 inline-flex min-h-12 items-center rounded-xl bg-foreground px-6 text-sm font-medium text-background focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-ring">Discuss your technical project →</Link></div><div className="rounded-2xl bg-muted p-7 sm:p-9"><h3 className="text-2xl tracking-tight">What you receive</h3><ul className="mt-6 space-y-5 text-base leading-7 text-muted-foreground"><li>A written scope, system map and agreed responsibilities.</li><li>The implemented connection, workflow or infrastructure.</li><li>Checks for the agreed success and failure paths.</li><li>Access, operational documentation and a practical handover.</li></ul><p className="mt-7 border-t border-border pt-5 text-sm leading-7 text-muted-foreground">Project price, provider subscriptions and support are scoped separately. Availability of any third-party tool is confirmed before it becomes a delivery commitment.</p></div></div></section>
 <section className="mx-auto max-w-[1440px] px-4 pb-24 sm:px-6"><h2 className="mb-10 text-4xl tracking-tight">The work we can take on.</h2><div className="grid gap-x-16 gap-y-9 md:grid-cols-2">{solutions.map(([heading,body,slug],i)=><article key={slug} className="border-t border-border pt-7"><p className="text-xs tabular-nums text-muted-foreground">0{i+1}</p><h3 className="mt-4 text-2xl tracking-tight">{heading}</h3><p className="mt-4 max-w-xl text-base leading-8 text-muted-foreground">{body}</p><Link href={`/services/${slug}`} className="mt-5 inline-flex min-h-11 items-center text-sm underline underline-offset-4">Explore {SERVICE_CATALOG.find(s=>s.slug===slug)?.name.toLowerCase()} →</Link></article>)}</div></section>
 <section className="mx-auto max-w-[1440px] px-4 pb-24 sm:px-6"><h2 className="text-4xl tracking-tight">From diagnosis to a working system.</h2><ol className="mt-10 grid gap-8 md:grid-cols-3">{[["Map the current state","Identify account owners, data flows, dependencies and the specific result the business needs."],["Build and verify","Implement in an appropriate test environment. Check permissions, retries, edge cases and the result in the destination system."],["Launch and hand over","Agree the rollout, recovery path and owner. Document how to operate, monitor and maintain the work."]].map(([h,b],i)=><li key={h} className="border-t border-border pt-6"><p className="text-xs text-muted-foreground">0{i+1}</p><h3 className="mt-4 text-2xl">{h}</h3><p className="mt-4 text-base leading-8 text-muted-foreground">{b}</p></li>)}</ol></section>
 <Faq heading="A few practical questions." lead="Scope, access and what happens after the connection is made." items={[{q:"Can you work with our existing tools?",a:"Yes. We first confirm the available APIs, permissions and plan requirements. The scope follows what the systems can actually support."},{q:"Can we start with diagnosis only?",a:"Yes. A technical consultation can review the problem and recommend the next step before you commission implementation."},{q:"Do you provide ongoing support?",a:"Support and monitoring can be agreed as a separate scope. The handover identifies who owns the accounts, documentation and operating responsibilities."}]}/>
 <ServiceReading service="other-tech-solutions"/><FinalCta/>
 </>}
