import { servicePhoto } from "@/content/service-groups";
import { ArrowButton } from "@/components/imageworks/arrow-button";
import Link from "next/link";
import Image from "next/image";
import { PageIntro } from "./page-intro";
import { Faq } from "./faq";
import { serviceOffer, servicePdf, serviceEnquiry, type ServiceCatalogEntry } from "@/lib/service-catalog";
const wrap = "mx-auto max-w-[1440px] px-4 sm:px-6";
export function SpecialistDetail({service:s}:{service:ServiceCatalogEntry}) {
  const o=serviceOffer(s);
  const flow="flow" in o ? o.flow : s.process;
  return <>
    <PageIntro label={s.name} title={s.title} lead={s.lead}/>
    <section className="pb-20 sm:pb-28"><div className={wrap}>
      <div className="grid border-y border-border sm:grid-cols-4">{flow.map((step,i)=><div key={step} className="flex items-center gap-4 border-b border-border py-5 sm:block sm:border-b-0 sm:pr-5"><span className="text-xs text-muted-foreground">0{i+1}</span><p className="sm:mt-3 text-lg tracking-tight">{step}</p></div>)}</div>
      <div className="mt-12 grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:gap-20"><div><h2 className="text-3xl tracking-tight sm:text-4xl">{o.name}</h2><p className="mt-5 text-xl leading-8">{o.summary}</p><p className="mt-4 text-base leading-7 text-muted-foreground">{o.fit}</p><div className="mt-8 flex flex-wrap items-center gap-6"><ArrowButton href={serviceEnquiry(s)} className="">{s.cta}</ArrowButton><a href={servicePdf(s)} download className="inline-flex min-h-11 items-center text-sm underline underline-offset-4">Download the pitch ↓</a></div><p className="mt-6 text-sm leading-6 text-muted-foreground">{o.firstStep}</p></div><div className="rounded-2xl bg-muted p-6 sm:p-9"><h2 className="text-xl">What you receive</h2><ol className="mt-5 divide-y divide-border">{o.deliverables.map((d,i)=><li key={d} className="flex gap-4 py-4 text-[15px] leading-7"><span className="text-xs text-muted-foreground">0{i+1}</span>{d}</li>)}</ol></div></div>
    </div></section>
    <section className="pb-20 sm:pb-28"><div className={wrap}><div className="grid gap-10 lg:grid-cols-[.6fr_1.4fr]"><h2 className="text-3xl tracking-tight sm:text-4xl">Where it fits.</h2><div>{s.sections.map(section=><article key={section.title} className="border-t border-border py-7 first:pt-0 first:border-0"><h3 className="text-2xl tracking-tight">{section.title}</h3><p className="mt-4 text-base leading-7 text-muted-foreground">{section.body}</p></article>)}</div></div>
    {s.slug==='jev-implementation' && <p className="mt-8 border-t border-border pt-6 text-sm leading-6 text-muted-foreground">Technology background: <a className="underline underline-offset-4" href="https://www.langchain.com/blog/building-a-harness-with-jev" target="_blank" rel="noopener noreferrer">LangChain’s guide to Jev</a> and <a className="underline underline-offset-4" href="https://www.langchain.com/blog/jev-agent-evals-langsmith" target="_blank" rel="noopener noreferrer">Jev agent evaluation</a>. These explain the technology; they are not endorsements of Fortitudo.</p>}
    </div></section>
    <section className="bg-muted/40 py-20 sm:py-28"><div className={wrap}><h2 className="text-3xl tracking-tight sm:text-4xl">Built, connected and checked.</h2><ol className="mt-10 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{s.process.map((step,i)=><li key={step} className="border-t border-border pt-5"><p className="text-xs text-muted-foreground">0{i+1}</p><p className="mt-4 text-base leading-7">{step}</p></li>)}</ol><div className="mt-14 grid gap-10 md:grid-cols-2"><div><h3 className="text-2xl tracking-tight">The handover has to demonstrate</h3><ul className="mt-5 list-disc space-y-3 pl-5 text-[15px] leading-7 text-muted-foreground">{o.acceptance.map(a=><li key={a}>{a}</li>)}</ul></div><div><h3 className="text-2xl tracking-tight">What determines the scope</h3><p className="mt-5 text-[15px] leading-7 text-muted-foreground">{o.scopeDrivers.join('. ')}.</p><p className="mt-4 text-[15px] leading-7 text-muted-foreground">{s.boundary}</p></div></div></div></section>
    <section className="py-20 sm:py-28"><div className={wrap}><div className="grid items-center gap-8 md:grid-cols-[160px_1fr_auto]"><Link href={`/resources/${s.resourceSlug}`} className="relative block aspect-[4/3] w-36"><Image src={servicePhoto(s.slug)} alt={`${s.name} editorial photograph`} fill sizes="160px" className="rounded-lg object-cover"/></Link><div><h2 className="text-3xl tracking-tight">Take the scope with you.</h2><p className="mt-4 max-w-xl text-base leading-7 text-muted-foreground">{s.inputs}</p><Link href={`/resources/${s.resourceSlug}`} className="mt-4 inline-flex min-h-11 items-center underline underline-offset-4">Read the service pitch →</Link></div><ArrowButton href={servicePdf(s)} download className="">Download PDF</ArrowButton></div></div></section>
    <Faq heading="Before we begin." items={o.faq}/>
    <section className="pb-24"><div className={wrap}><div className="flex flex-wrap items-center justify-between gap-8 border-t border-border pt-10"><div><h2 className="text-3xl tracking-tight">Bring us the task.</h2><p className="mt-3 text-muted-foreground">We will define the implementation and give you a written proposal.</p></div><ArrowButton href={serviceEnquiry(s)} className="">{s.cta}</ArrowButton></div><Link href="/services" className="mt-8 inline-flex min-h-11 items-center text-sm underline underline-offset-4">Explore the other AI engagements →</Link></div></section>
  </>;
}
